### ISSUE TITLE
PDF exports of .sketch files in repo

### ISSUE THREAD

**Issue by mpcnat** [productof/brand#2]
Can we get PDF exports of the .sketch assets for us non sketch users please.
Just so we can see content 😄 
I'm a poor AdobeXD and FramerJS user 😈

**Comment by lukebrooker** [comment]
Short term you could use https://github.com/AnimaApp/sketch-web-viewer/ ?

We’d just have to make sure all files are exported to pdf on commit

**Comment by mpcnat** [comment]
Add Bitmap PDFs in PR #5 via online viewer/screenshot/saved-as-pdf until someone does it via sketch for real.

**Comment by mpcnat** [comment]
I created XD versions in new PR, so I'm going to close this issue as I don't think we need anything else here.
